# Generated by Django 4.2.1 on 2023-12-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locationid', models.IntegerField(blank=True, null=True)),
                ('Applicant', models.CharField(blank=True, max_length=255, null=True)),
                ('FacilityType', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_api.cluster')),
            ],
        ),
    ]
