# Generated by Django 4.2.1 on 2023-12-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('Applicant', models.CharField(max_length=255)),
                ('FacilityType', models.CharField(max_length=255)),
                ('cnn', models.IntegerField()),
                ('locationDescription', models.TextField()),
                ('Address', models.CharField(max_length=255)),
                ('blocklot', models.IntegerField()),
                ('block', models.CharField(max_length=10)),
                ('lot', models.CharField(max_length=10)),
                ('permit', models.CharField(max_length=20)),
                ('Received', models.IntegerField()),
                ('ExpirationDate', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_api.cluster')),
            ],
        ),
    ]
