# Generated by Django 4.2.1 on 2023-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtruck',
            name='locationDescription',
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='ExpirationDate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='FacilityType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='Location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='Received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='blocklot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='cnn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='locationid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='lot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='permit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
